# Signature of the root hash, with the image signing key, slot A (its size
# is set by systemd-repart)
[Partition]
Type=root-verity-sig
# The label has 36 characters at most (GPT): usb-pasteur_<14 digits>_veritysig
Label=usb-pasteur_%A_veritysig
Verity=signature
VerityMatchKey=root
