# The initrd of the image: the default initrd of mkosi, with a reboot instead
# of an emergency shell (see mkosi.extra/)

[Include]
Include=mkosi-initrd

[Content]
ExtraTrees=%D/mkosi.images/initrd/mkosi.extra
